// Compact recipe authoring -> src/data/recipes.json. Edit recipes.json directly, or add a line here and run `npm run recipes`.
// R(id, name, category, description, stepKind, tags, [kcal, protein, carbs, fat, sodium], "Name,amount,unit,Group;...")  (amounts are for 1 serving)
// Groups: V=Vegetables R=Protein A=Aromatics P=Pantry X=not on grocery list (water)
import fs from 'node:fs';
const G = { V: 'Vegetables', R: 'Protein', A: 'Aromatics', P: 'Pantry', X: 'Hidden' };
const S = {
  saute: ['Wash and cut the vegetables into bite-size pieces. Mince the garlic; slice the onion and tomato.', 'Heat {oil} of oil in a non-stick pan over medium heat.', 'Sauté the garlic, onion and tomato for 2 minutes until soft.', 'Add the main vegetables and {water} of water. Cover and simmer 8–10 minutes until tender.', 'Season with the salt and a pinch of pepper. Taste, then serve warm with rice.'],
  stew: ['Cut the protein into small pieces and prep the vegetables and aromatics.', 'Heat {oil} of oil in a non-stick pot. Sauté garlic, onion and ginger until fragrant.', 'Add the protein and cook 3 minutes until it turns opaque.', 'Pour in {water} of water, add the vegetables, cover and simmer 12–15 minutes until tender.', 'Season lightly, taste, and serve with rice.'],
  soup: ['Prep all ingredients: slice, cube or mince as needed.', 'Heat {oil} of oil in a pot and sauté garlic, onion and ginger until fragrant.', 'Add the protein or beans and stir for 2–3 minutes.', 'Pour in {water} of water and bring to a boil. Lower the heat and simmer 15–20 minutes until everything is soft.', 'Add the leafy greens for the last 2 minutes. Season lightly and serve hot.'],
  grill: ['Pat the main ingredient dry. Mix with the calamansi, pepper and minced garlic.', 'Lightly brush the grill pan or the food with {oil} of oil.', 'Grill over medium heat 4–6 minutes per side until cooked through and lightly charred.', 'Slice the tomato and onion and serve fresh on the side, with rice.'],
  steam: ['Slice the ginger, onion and vegetables. Place them on a heatproof plate with the fish.', 'Drizzle with {oil} of oil, the calamansi and the salt.', 'Steam over boiling water 10–12 minutes until the fish flakes easily.', 'Serve hot with the pan juices and rice.'],
  torta: ['Char the eggplant over a flame, or roast at 200°C for 20 minutes, until soft. Peel it, keeping the stem.', 'Flatten the flesh gently with a fork.', 'Beat the egg with the chopped onion and salt.', 'Dip the eggplant in the egg. Cook in a non-stick pan brushed with {oil} of oil (or air-fry at 180°C for 6–8 minutes), flipping once, until set.', 'Serve warm with sliced fresh tomato.'],
};
const adobo = ['Combine chicken, garlic, onion, vinegar, low-sodium soy sauce, pepper and bay leaf. Marinate 15 minutes.', 'Heat {oil} of oil and lightly sear the chicken.', 'Add the marinade and {water} of water. Bring to a boil without stirring for 2 minutes, then simmer 20 minutes.', 'Reduce the sauce slightly, taste, and serve with rice.'];
const vsoup = ['Cube the potato, chayote and carrots; shred the cabbage; slice the celery.', 'Heat {oil} of oil, sauté garlic and onion for 1 minute.', 'Add the potato, chayote, carrots and {water} of water. Boil, then simmer 12 minutes.', 'Add the cabbage and celery; cook 5 more minutes. Season lightly and serve hot.'];
const A = 'Garlic,3,g,A;Onion,20,g,A;';
const out = [];
const R = (id, name, category, description, kind, words, n, ing, steps) => {
  const ingredients = ing.split(';').map((x) => { const [nm, a, u, g] = x.split(','); return { name: nm, amount: +a, unit: u, group: G[g] }; });
  const oil = ingredients.find((i) => i.name === 'Cooking oil')?.amount || 0;
  const [calories, protein, carbohydrates, fat, sodium] = n;
  const tags = [...new Set([...words.split(' '), category.toLowerCase(), ...(sodium <= 350 ? ['low-sodium'] : []), ...(protein <= 20 ? ['lower-protein'] : []), ...(oil <= 5 ? ['low-oil'] : [])])];
  out.push({ id, name, category, description, servings: 1, ingredients, nutrition: { calories, protein, carbohydrates, fat, sodium }, oil, instructions: steps || S[kind], tags });
};
R('ginisang-sayote', 'Ginisang Sayote', 'Vegetable', 'Tender sayote sautéed with garlic, onion and tomato in just a touch of oil.', 'saute', 'stir-fry saute', [90, 2, 13, 5, 220], `Sayote,150,g,V;Tomato,30,g,V;${A}Cooking oil,5,ml,P;Water,60,ml,X;Salt,0.5,g,P`);
R('ginisang-pechay', 'Ginisang Pechay', 'Vegetable', 'Crisp-tender pechay with garlic and tomato. Ready in ten minutes.', 'saute', 'stir-fry saute', [85, 3, 8, 5, 240], `Pechay,150,g,V;Tomato,30,g,V;${A}Cooking oil,5,ml,P;Water,40,ml,X;Salt,0.5,g,P`);
R('ginisang-repolyo', 'Ginisang Repolyo', 'Vegetable', 'Sweet cabbage and carrots, lightly sautéed.', 'saute', 'stir-fry saute', [95, 2, 12, 5, 230], `Cabbage,130,g,V;Carrots,30,g,V;Tomato,30,g,V;${A}Cooking oil,5,ml,P;Water,50,ml,X;Salt,0.5,g,P`);
R('ginisang-ampalaya', 'Ginisang Ampalaya', 'Vegetable', 'Ampalaya with tomato and onion. Slice thin to soften the bitterness.', 'saute', 'stir-fry saute', [90, 3, 9, 5, 230], `Ampalaya,120,g,V;Tomato,50,g,V;${A}Cooking oil,5,ml,P;Water,50,ml,X;Salt,0.5,g,P`);
R('ginisang-kalabasa', 'Ginisang Kalabasa', 'Vegetable', 'Sweet kalabasa with string beans, gently simmered.', 'saute', 'stir-fry saute', [110, 3, 18, 5, 225], `Kalabasa (squash),150,g,V;String beans,30,g,V;${A}Cooking oil,5,ml,P;Water,80,ml,X;Salt,0.5,g,P`);
R('ginisang-upo', 'Ginisang Upo', 'Vegetable', 'Soft, juicy upo with garlic, onion and tomato.', 'saute', 'stir-fry saute', [85, 2, 11, 5, 220], `Upo,150,g,V;Tomato,30,g,V;${A}Cooking oil,5,ml,P;Water,40,ml,X;Salt,0.5,g,P`);
R('ginisang-patola', 'Ginisang Patola', 'Vegetable', 'Light and silky patola sautéed with tomato.', 'saute', 'stir-fry saute', [85, 2, 10, 5, 220], `Patola,130,g,V;Tomato,30,g,V;${A}Cooking oil,5,ml,P;Water,40,ml,X;Salt,0.5,g,P`);
R('tortang-talong', 'Tortang Talong', 'Egg', 'Smoky charred eggplant in a fluffy egg coating, pan-cooked with a little oil.', 'torta', 'egg saute', [150, 8, 10, 9, 210], 'Eggplant,150,g,V;Egg,1,pc,R;Onion,15,g,A;Tomato,40,g,V;Cooking oil,5,ml,P;Salt,0.5,g,P');
R('low-oil-tortang-talong', 'Low-oil Tortang Talong', 'Egg', 'The same comfort torta, baked or air-fried with barely any oil.', 'torta', 'egg bake airfry', [125, 7, 10, 6, 200], 'Eggplant,150,g,V;Egg,1,pc,R;Onion,15,g,A;Tomato,40,g,V;Cooking oil,2,ml,P;Salt,0.4,g,P');
R('grilled-eggplant-tomato-onion', 'Grilled Eggplant with Tomato and Onion', 'Vegetable', 'Grilled eggplant topped with fresh tomato, onion and calamansi.', 'grill', 'grill', [80, 2, 14, 2, 150], 'Eggplant,150,g,V;Tomato,60,g,V;Onion,30,g,A;Garlic,3,g,A;Calamansi juice,10,ml,P;Cooking oil,2,ml,P;Salt,0.3,g,P;Black pepper,0.3,g,P');
R('pinakbet-style-vegetables', 'Pinakbet-style Vegetables', 'Vegetable', 'Squash, eggplant, ampalaya, okra and beans in a light tomato broth.', 'saute', 'stir-fry saute', [105, 3, 17, 5, 240], 'Kalabasa (squash),60,g,V;Eggplant,50,g,V;Ampalaya,30,g,V;String beans,40,g,V;Okra,30,g,V;Tomato,30,g,V;Garlic,3,g,A;Onion,15,g,A;Cooking oil,5,ml,P;Water,60,ml,X;Salt,0.5,g,P');
R('chicken-tinola', 'Chicken Tinola', 'Chicken', 'Ginger-scented chicken soup with sayote and malunggay.', 'soup', 'soup boil', [165, 19, 10, 5, 300], 'Chicken breast,80,g,R;Sayote,100,g,V;Malunggay leaves,15,g,V;Ginger,10,g,A;Garlic,3,g,A;Onion,20,g,A;Cooking oil,3,ml,P;Water,300,ml,X;Salt,0.8,g,P');
R('chicken-with-sayote', 'Chicken with Sayote', 'Chicken', 'Simple stewed chicken and sayote in its own light broth.', 'stew', 'stir-fry saute', [160, 19, 10, 5, 310], `Chicken breast,80,g,R;Sayote,120,g,V;Ginger,5,g,A;${A}Cooking oil,3,ml,P;Water,150,ml,X;Salt,0.8,g,P`);
R('chicken-with-cabbage', 'Chicken with Cabbage', 'Chicken', 'Tender chicken with cabbage and carrots, lightly sautéed and simmered.', 'stew', 'stir-fry saute', [165, 19, 10, 5, 300], `Chicken breast,80,g,R;Cabbage,120,g,V;Carrots,30,g,V;Ginger,5,g,A;${A}Cooking oil,3,ml,P;Water,100,ml,X;Salt,0.8,g,P`);
R('reduced-sodium-chicken-adobo', 'Reduced-sodium Chicken Adobo', 'Chicken', 'Classic adobo flavor, with just a little low-sodium soy sauce and more vinegar and garlic.', 'stew', 'saute', [175, 19, 4, 8, 340], 'Chicken breast,80,g,R;Garlic,5,g,A;Onion,20,g,A;Vinegar,20,ml,P;Low-sodium soy sauce,5,ml,P;Bay leaf,1,pc,P;Whole peppercorns,1,g,P;Cooking oil,3,ml,P;Water,100,ml,X', adobo);
R('chicken-afritada-style', 'Chicken Afritada-style with Minimal Oil', 'Chicken', 'Tomato-based chicken stew with potato, carrots and bell pepper.', 'stew', 'saute', [210, 20, 20, 5, 310], `Chicken breast,80,g,R;Tomato,60,g,V;Potato,60,g,V;Carrots,40,g,V;Bell pepper,30,g,V;${A}Cooking oil,3,ml,P;Water,120,ml,X;Salt,0.8,g,P`);
R('steamed-fish-with-ginger', 'Steamed Fish with Ginger', 'Fish', 'Delicate white fish steamed with ginger, onion and tomato.', 'steam', 'steam', [130, 19, 4, 4, 190], 'Fish fillet,90,g,R;Ginger,10,g,A;Onion,20,g,A;Tomato,30,g,V;Calamansi juice,10,ml,P;Cooking oil,2,ml,P;Salt,0.5,g,P');
R('grilled-fish-calamansi', 'Grilled Fish with Calamansi', 'Fish', 'Fish grilled with calamansi and garlic, served with fresh tomato and onion.', 'grill', 'grill', [135, 19, 4, 4, 150], 'Fish fillet,90,g,R;Calamansi juice,15,ml,P;Garlic,3,g,A;Onion,20,g,A;Tomato,30,g,V;Cooking oil,2,ml,P;Black pepper,0.3,g,P');
R('fish-tomato-onion', 'Fish with Tomato and Onion', 'Fish', 'Fish gently simmered with lots of tomato and onion.', 'stew', 'saute', [150, 19, 6, 5, 220], 'Fish fillet,90,g,R;Tomato,80,g,V;Onion,30,g,A;Ginger,5,g,A;Cooking oil,3,ml,P;Water,60,ml,X;Salt,0.5,g,P');
R('steamed-fish-with-vegetables', 'Steamed Fish with Vegetables', 'Fish', 'A one-plate steamed dinner of fish, carrots and cabbage.', 'steam', 'steam', [145, 20, 9, 4, 230], 'Fish fillet,90,g,R;Carrots,40,g,V;Cabbage,60,g,V;Ginger,8,g,A;Onion,15,g,A;Calamansi juice,8,ml,P;Cooking oil,2,ml,P;Salt,0.5,g,P');
R('tofu-mixed-vegetables', 'Tofu with Mixed Vegetables', 'Tofu', 'Soft tofu with colorful vegetables in a light garlicky sauce.', 'saute', 'stir-fry saute', [155, 9, 12, 8, 220], `Firm tofu,80,g,R;Carrots,30,g,V;Cabbage,60,g,V;String beans,30,g,V;${A}Low-sodium soy sauce,3,ml,P;Cooking oil,5,ml,P;Water,60,ml,X`);
R('ginisang-tofu-vegetables', 'Ginisang Tofu with Vegetables', 'Tofu', 'Golden ginisa-style tofu with pechay and tomato.', 'saute', 'stir-fry saute', [150, 9, 8, 8, 200], `Firm tofu,80,g,R;Pechay,80,g,V;Tomato,30,g,V;${A}Cooking oil,5,ml,P;Water,50,ml,X;Salt,0.5,g,P`);
R('monggo-with-vegetables', 'Monggo with Vegetables', 'Soup', 'Warm monggo stew with kalabasa and leafy greens.', 'soup', 'soup boil', [190, 11, 30, 3, 260], 'Mung beans (dry),40,g,R;Kalabasa (squash),40,g,V;Malunggay leaves,30,g,V;Tomato,30,g,V;Ginger,3,g,A;Garlic,3,g,A;Onion,20,g,A;Cooking oil,3,ml,P;Water,300,ml,X;Salt,0.8,g,P');
R('vegetable-soup', 'Vegetable Soup', 'Soup', 'A light, comforting soup of potato, chayote, carrots and cabbage.', 'soup', 'soup boil', [95, 3, 20, 2, 260], 'Potato,50,g,V;Sayote,60,g,V;Carrots,40,g,V;Cabbage,60,g,V;Celery,10,g,V;Garlic,3,g,A;Onion,20,g,A;Cooking oil,2,ml,P;Water,350,ml,X;Salt,0.8,g,P', vsoup);
fs.writeFileSync(new URL('../src/data/recipes.json', import.meta.url), JSON.stringify(out, null, 1));
console.log(out.length + ' recipes written');
